#!/usr/bin/env bash
set -euo pipefail

CSS_FILE="src/styles/colors.css"

mapfile -t VARS < <(
  sed -n '/:root\s*{/,/}/p' "$CSS_FILE" |
    grep -E '^\s*--[a-z0-9-]+:' |
    sed -E 's/^\s*--([a-z0-9-]+):.*$/\1/'
)

THEME_BLOCK="@theme inline {\n"
for NAME in "${VARS[@]}"; do
  THEME_BLOCK+="  --color-$NAME: var(--$NAME);\n"
done
THEME_BLOCK+="}"

if grep -q '@theme inline' "$CSS_FILE"; then
  awk -v newBlock="$THEME_BLOCK" '
    BEGIN { inBlock = 0 }
    # start of theme block?
    /@theme inline\s*{/ {
      print newBlock
      inBlock = 1
      next
    }
    # end of block?
    inBlock && /^\s*}\s*$/ {
      inBlock = 0
      next
    }
    # skip old block lines
    inBlock { next }
    # everything else prints through
    { print }
  ' "$CSS_FILE" >"${CSS_FILE}.tmp" &&
    mv "${CSS_FILE}.tmp" "$CSS_FILE"
else
  {
    echo
    printf "%b\n" "$THEME_BLOCK"
  } >>"$CSS_FILE"
fi

echo "✅ Updated '$CSS_FILE' with @theme inline mapping."

# --- Generate TypeScript type file ---
TS_FILE="src/types/color.types.ts"

# Collect non-shadow color names
COLOR_NAMES=()
for NAME in "${VARS[@]}"; do
  if [[ "$NAME" == shadow-* ]]; then
    continue
  fi
  COLOR_NAMES+=("$NAME")
done

# Build union body: tab-indented, double-quoted, trailing semicolon on last
UNION_LINES=()
LAST_INDEX=$((${#COLOR_NAMES[@]} - 1))
for i in "${!COLOR_NAMES[@]}"; do
  NAME="${COLOR_NAMES[$i]}"
  if [[ $i -eq $LAST_INDEX ]]; then
    UNION_LINES+=("\t| \"$NAME\";")
  else
    UNION_LINES+=("\t| \"$NAME\"")
  fi
done

UNION_BODY=$(
  IFS=$'\n'
  echo "${UNION_LINES[*]}"
)

TS_CONTENT="// ⚠️ AUTO-GENERATED by generate-theme-aliases.sh — do not edit manually
// Source: $CSS_FILE

export type ColorName =\n${UNION_BODY}\n\nexport type ColorRecord = Record<ColorName, string>;\n"

# Write only if content changed
if [[ ! -f "$TS_FILE" ]] || ! cmp -s <(printf "%b" "$TS_CONTENT") "$TS_FILE"; then
  printf "%b" "$TS_CONTENT" >"$TS_FILE"
  echo "✅ Generated '$TS_FILE' with ColorName type."
else
  echo "✓ '$TS_FILE' is already up to date."
fi
